### ISSUE TITLE
how to use fast-dds-monitor

### ISSUE THREAD

**Issue by YGD159** [eProsima/Fast-DDS-monitor#114]
How to deal with the problem?
I can't find the infomation about physical.
![lALPDhmOwlTjAJzNA6fNBak_1449_935 png_620x10000q90g](https://user-images.githubusercontent.com/52145923/130193802-1422adc1-0def-4e31-9679-4d204508d58d.jpg)

**Comment by jparisu** [comment]
Hi @YGD159 

Glad to know that you are using Fast DDS Monitor.

My first approach is that you have not enabled statistics when configuring the Shapes Demo application.
Be sure that you active the checkbox `Active Statistics` in the `Options->Participant Configuration` window: https://eprosima-shapes-demo.readthedocs.io/en/stable/first_steps/first_steps.html#participant-configuration .
In case the Participant is already running, you would need to `Stop` and `Start` the Participant in order for this configuration to take place.

In case this does not fix the issue, please retrieve further information about the configuration that you are using in both Shapes Demo and Fast DDS Monitor, and the steps that you have followed.

**Comment by YGD159** [comment]
> 嗨@YGD159
> 
> 很高兴知道您正在使用 Fast DDS Monitor。
> 
> 我的第一种方法是您在配置 Shapes Demo 应用程序时没有启用统计信息。
> 确保您激活`Active Statistics`了`Options->Participant Configuration`窗口中的复选框：[https](https://eprosima-shapes-demo.readthedocs.io/en/stable/first_steps/first_steps.html#participant-configuration) : [//eprosima-shapes-demo.readthedocs.io/en/stable/first_steps/first_steps.html#participant-configuration](https://eprosima-shapes-demo.readthedocs.io/en/stable/first_steps/first_steps.html#participant-configuration)。
> 如果 Participant 已经在运行，您需要`Stop`和`Start`Participant 才能进行此配置。
> 
> 如果这不能解决问题，请检索有关您在 Shapes Demo 和 Fast DDS Monitor 中使用的配置以及您遵循的步骤的更多信息。
