### ISSUE TITLE
Update of statistics

### ISSUE THREAD

**Issue by Heyangq** [eProsima/Fast-DDS-monitor#162]
I am used a dynamical chartin DATA_COUNT topic with 1 second of update periodand using SUM as Statistical Kind.
However, the data was not updated according to my expectation, so it could not reflect the frequency of data publish well.
The SUM value takes more than 1min to update, but I hope it can be updated quickly (between 1 second and 3second).

The current data publication frequency is 300Hz.

All 10 participants publish data at the same time.

The total amount of data is about 300 bytes.
![888](https://user-images.githubusercontent.com/111166180/185068981-02abaf89-fa02-47e7-8d5a-cec360629a30.jpg)

**Comment by jparisu** [comment]
Hi @Heyangq 

I have been able to reproduce your error, it seems like a bug of Fast DDS Statistics Module.

It seems like the frequency with which Fast DDS publishes DATA_COUNT topic is not constant, and this makes that there are peaks in the plot.
And it also seems like whenever there are more than 1 DataWriter, some data on this topic is not correctly sent or received.

I would open an issue in Fast DDS and we will work on it ASAP.

**Comment by Heyangq** [comment]
> 嗨@Heyangq
> 
> 我已经能够重现您的错误，这似乎是快速DDS统计模块的错误。
> 
> 似乎Fast DDS发布DATA_COUNT主题的频率不是恒定的，这使得情节中存在峰值。而且似乎每当有超过1个DataWriter时，有关此主题的一些数据都不会正确发送或接收。
> 
> 我会在Fast DDS中打开一个问题，我们将尽快解决它。

Thank you very much for your reply. 
I hope this problem can be solved as soon as possible. 
Wish you all the best
