### ISSUE TITLE
Failed to access eProsima's page

### ISSUE THREAD

**Issue by atinfinity** [eProsima/Fast-DDS-monitor#226]
I read <https://fast-dds-monitor.readthedocs.io/en/latest/rst/installation/linux.html> to use Fast DDS Monitor.
But, I could not access <https://www.eprosima.com/>. Is this a temporary issue?

**Comment by Jackie2chen** [comment]
+1

**Comment by Jackie2chen** [comment]
did you find the way to install Fast DDS Monitor?

**Comment by rsanchez15** [comment]
@atinfinity @Jackie2chen are you still experiencing the same issue with the eProsima's website?

**Comment by Jackie2chen** [comment]
yes

> @atinfinity @Jackie2chen are you still experiencing the same issue with the eProsima's website?

**Comment by mlsdpk** [comment]
Are there any updates on this? I'm also having issues accessing eProsima's site to download the monitor.

**Comment by atinfinity** [comment]
I can access <https://www.eprosima.com/>. So, I closed this issue.
